export const products = [
  {
    id: "starters-bruschetta",
    image: "/assets/bruschetta.jpg",
    title: "Bruschetta",
    price: 6,
    kcal: "110 kcal",
    description:
      "Mixture of chopped tomatoes, balsamic, basil, and garlic, spooned over olive-oil brushed slices of rustic bread.",
    dietary: {
      energy: "666 kcal / 2787 kJ",
      allergens: "Soya, Gluten",
    },
    contain: "Possible kitchen cross-contamination: Gluten (Rye)",
    nutrition: {
      energy: "666 kcal",
      fat: "40.4g",
      protein: "8.7g",
      salt: "1.37g",
      carbohydrates: "68.1g",
      fibre: "3.3g",
    },
  },
  {
    id: "starters-caprese-salad",
    image: "/assets/capresse.jpg",
    title: "Caprese salad",
    price: 9,
    kcal: "88 kcal",
    description:
      "“Insalata Caprese” - “the salad of Capri”, popular on Italian islands. Slices of fresh mozzarella cheese, tomatoes, and basil, then seasoned to perfection, drizzled with extra virgin olive oil.",
    dietary: {
      energy: "362 kcal / 1515 kJ",
      allergens: "Milk",
    },
    contain: "Possible kitchen cross-contamination: Milk",
    nutrition: {
      energy: "362 kcal",
      fat: "15.4g",
      protein: "9.7g",
      salt: "1.35g",
      carbohydrates: "47.1g",
      fibre: "5.3g",
    },
  },
  {
    id: "starters-filled-eggs",
    image: "/assets/eggs.jpg",
    title: "Filled Eggs",
    price: 11,
    kcal: "123 kcal",
    description:
      "Single layer of eggs covered with a mix of tuna, Dijon mustard, green onions and a pinch of lemon.",
    dietary: {
      energy: "666 kcal / 2787 kJ",
      allergens: "Soya, Gluten",
    },
    contain: "Possible kitchen cross-contamination: Gluten (Rye)",
    nutrition: {
      energy: "666 kcal",
      fat: "40.4g",
      protein: "8.7g",
      salt: "1.37g",
      carbohydrates: "68.1g",
      fibre: "3.3g",
    },
  },
  {
    id: "starters-omelette",
    image: "/assets/omleta.jpg",
    title: "Omelette",
    price: 12,
    kcal: "133 kcal",
    description:
      "Fresh eggs smashed and seasoned with salad, avocado slices, parsley and mushrooms.",
    dietary: {
      energy: "362 kcal / 1515 kJ",
      allergens: "Ovalbumin, ovomucoid, ovotransferrin, lysozyme",
    },
    contain:
      "Possible kitchen cross-contamination in egg white: ovalbumin, ovomucoid, ovotransferrin, lysozyme",
    nutrition: {
      energy: "362 kcal",
      fat: "15.4g",
      protein: "9.7g",
      salt: "1.35g",
      carbohydrates: "47.1g",
      fibre: "5.3g",
    },
  },
  {
    id: "starters-spinach-rolls",
    image: "/assets/spinach.jpg",
    title: "Spinach Rolls",
    price: 11,
    kcal: "133 kcal",
    description:
      "Colorful and delicious appetizer with a layer of smashed spinach mix, flour, yogurt and butter.",
    dietary: {
      energy: "666 kcal / 2787 kJ",
      allergens: "Histamines, Gluten, Milk",
    },
    contain: "Possible kitchen cross-contamination: Histamines, Gluten, Milk",
    nutrition: {
      energy: "666 kcal",
      fat: "40.4g",
      protein: "8.7g",
      salt: "1.37g",
      carbohydrates: "68.1g",
      fibre: "3.3g",
    },
  },
  {
    id: "soups-greek-chicken",
    image: "/assets/greek.jpg",
    title: "Greek chicken soup",
    price: 23,
    kcal: "433 kcal",
    description:
      "A bowl of soup made from chicken, carrot, parsley, parsnips, garlic, sour cream and celery root.",
    dietary: {
      energy: "433 kcal / 4787 kJ",
      allergens: "Garlic intolerance",
    },
    contain: "Possible kitchen cross-contamination: Garlic intolerance",
    nutrition: {
      energy: "666 kcal",
      fat: "40.4g",
      protein: "8.7g",
      salt: "1.37g",
      carbohydrates: "68.1g",
      fibre: "3.3g",
    },
  },
  {
    id: "soups-meatball",
    image: "/assets/meatball.jpg",
    title: "Meatball soup",
    price: 21,
    kcal: "230 kcal",
    description:
      "A bowl of soup made from a mix of vegetables and tasty meatballs.",
    dietary: {
      energy: "230 kcal / 2780 kJ",
      allergens: "Wheat, gluten",
    },
    contain: "Possible kitchen cross-contamination: wheat, gluten",
    nutrition: {
      energy: "666 kcal",
      fat: "40.4g",
      protein: "8.7g",
      salt: "1.37g",
      carbohydrates: "68.1g",
      fibre: "3.3g",
    },
  },
  {
    id: "soups-chicken",
    image: "/assets/chicken.jpg",
    title: "Chicken soup",
    price: 20,
    kcal: "333 kcal",
    description:
      "A flavoured bowl of boiled chicken breast seasoned with onions,carrots, celery root and tiny rolls of pastas.",
    dietary: {
      energy: "333 kcal / 3787 kJ",
      allergens: "Wheat, gluten",
    },
    contain: "Possible kitchen cross-contamination: wheat, gluten",
    nutrition: {
      energy: "666 kcal",
      fat: "40.4g",
      protein: "8.7g",
      salt: "1.37g",
      carbohydrates: "68.1g",
      fibre: "3.3g",
    },
  },
  {
    id: "grill-chicken",
    image: "/assets/grilled-chicken.jpg",
    title: "Grilled chicken",
    price: 27,
    kcal: "433 kcal",
    description:
      "A piece of juicy chicken served with golden potatoes and a slice of lemon.",
    dietary: {
      energy: "433 kcal / 4787 kJ",
      allergens: "Patatin, solanine",
    },
    contain: "Possible kitchen cross-contamination: patatin, solanine",
    nutrition: {
      energy: "433 kcal",
      fat: "40.4g",
      protein: "8.7g",
      salt: "1.37g",
      carbohydrates: "68.1g",
      fibre: "3.3g",
    },
  },
  {
    id: "grill-beef",
    image: "/assets/beef.jpg",
    title: "Grilled beef",
    price: 29,
    kcal: "533 kcal",
    description:
      "Big slice of beef cooked well-done in a mix of herbs and served with golden wedges.",
    dietary: {
      energy: "533 kcal / 5787 kJ",
      allergens: "Patatin, solanine",
    },
    contain: "Possible kitchen cross-contamination: patatin, solanine",
    nutrition: {
      energy: "533 kcal",
      fat: "40.4g",
      protein: "8.7g",
      salt: "1.37g",
      carbohydrates: "68.1g",
      fibre: "3.3g",
    },
  },
  {
    id: "grill-lamb",
    image: "/assets/lamb.jpg",
    title: "Grilled lamb",
    price: 20,
    kcal: "333 kcal",
    description:
      "Juicy lamb cooked well-done in a mix of herbs and served with steamed broccoli and baked baby potatoes.",
    dietary: {
      energy: "333 kcal / 3787 kJ",
      allergens: "Patatin, solanine",
    },
    contain: "Possible kitchen cross-contamination: patatin, solanine",
    nutrition: {
      energy: "666 kcal",
      fat: "40.4g",
      protein: "8.7g",
      salt: "1.37g",
      carbohydrates: "68.1g",
      fibre: "3.3g",
    },
  },
  {
    id: "grill-fish",
    image: "/assets/fish.jpg",
    title: "Grilled fish",
    price: 15,
    kcal: "303 kcal",
    description:
      "Fresh fish grilled in a mix of seasoned herbs and served with lemon.",
    dietary: {
      energy: "303 kcal / 3707 kJ",
      allergens: "Patatin, solanine",
    },
    contain: "Possible kitchen cross-contamination: patatin, solanine",
    nutrition: {
      energy: "666 kcal",
      fat: "40.4g",
      protein: "8.7g",
      salt: "1.37g",
      carbohydrates: "68.1g",
      fibre: "3.3g",
    },
  },
];
